name: Debug Secrets

on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        env:
          REGISTRANT_USER_NAME: "${{ secrets.REGISTRANT_USER_NAME }}"
          REGISTRANT_PASSWORD: "${{ secrets.REGISTRANT_PASSWORD }}"
        run: |
          echo "REGISTRANT_USER_NAME is set"
          echo "REGISTRANT_PASSWORD is set"
