name: Debug Secrets

on: push

env:
  MY_SUPER_REPO_SECRET: ${{ secrets.MY_SUPER_REPO_SECRET }}
  PRO_USER_NAME: ${{ secrets.PRO_USER_NAME }}
  PRO_USER_PASSWORD: ${{ secrets.PRO_USER_PASSWORD }}
  REGISTRANT_USER_NAME: ${{ secrets.REGISTRANT_USER_NAME }}
  REGISTRANT_PASSWORD: ${{ secrets.REGISTRANT_PASSWORD }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          python verify_secrets_accessible2.py
