name: Scheduler1 case_register.py

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run case_register.py
        run: python case_register.py



      - name: Run case_register.py
        run: python case_register.py

      - name: Run case_register.py
        run: python case_register.py
