name: Schedule case_register.py

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
# schedule:
#  - cron: '1 10 * * *' # 10:01 AM UTC every day
#  - cron: '*/10 * * * *' # Every 10 minutes

on: push

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies with uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv install

      - name: Run case_register.py
        env:
          PRO_USER_NAME: ${{ secrets.PRO_USER_NAME }}
          PRO_USER_PASSWORD: ${{ secrets.PRO_USER_PASSWORD }}
          REGISTRANT_USER_NAME: ${{ secrets.REGISTRANT_USER_NAME }}
          REGISTRANT_USER_PASSWORD: ${{ secrets.REGISTRANT_USER_PASSWORD }}
        run: python case_register.py
