name: Register user for session.
on: push
# on:
#   schedule:
#     - cron: '15 20 * * *' # Runs daily at 20:15 UTC, which is 16:15 EST.
env:
  PRO_USER_NAME: ${{ secrets.PRO_USER_NAME }}
  PRO_USER_PASSWORD: ${{ secrets.PRO_USER_PASSWORD }}
  REGISTRANT_USER_NAME: ${{ secrets.REGISTRANT_USER_NAME }}
  REGISTRANT_USER_PASSWORD: ${{ secrets.REGISTRANT_USER_PASSWORD }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies with uv
        run: |
          uv sync
          source .venv/bin/activate
          python -m playwright install

      - name: Run hq.py
        run: |
          source .venv/bin/activate
          python hq.py
